/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author carli
 */
public class FrmChooseComputer extends javax.swing.JFrame {

    /**
     * Creates new form FrmStudentStart
     */
    public FrmChooseComputer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPC = new utilities.MenuButton();
        btnPC1 = new utilities.MenuButton();
        btnPC2 = new utilities.MenuButton();
        btnPC3 = new utilities.MenuButton();
        btnPC4 = new utilities.MenuButton();
        btnPC5 = new utilities.MenuButton();
        jPanel3 = new javax.swing.JPanel();
        btnPC6 = new utilities.MenuButton();
        btnPC7 = new utilities.MenuButton();
        btnPC8 = new utilities.MenuButton();
        btnPC9 = new utilities.MenuButton();
        btnPC10 = new utilities.MenuButton();
        btnPC11 = new utilities.MenuButton();
        jPanel5 = new javax.swing.JPanel();
        btnPC12 = new utilities.MenuButton();
        btnPC13 = new utilities.MenuButton();
        btnPC14 = new utilities.MenuButton();
        btnPC15 = new utilities.MenuButton();
        btnPC16 = new utilities.MenuButton();
        btnPC17 = new utilities.MenuButton();
        jPanel6 = new javax.swing.JPanel();
        lblPc = new javax.swing.JLabel();
        lblPc1 = new javax.swing.JLabel();
        lblPc2 = new javax.swing.JLabel();
        lblPc3 = new javax.swing.JLabel();
        lblPc4 = new javax.swing.JLabel();
        lblPc5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblPc12 = new javax.swing.JLabel();
        lblPc13 = new javax.swing.JLabel();
        lblPc14 = new javax.swing.JLabel();
        lblPc15 = new javax.swing.JLabel();
        lblPc16 = new javax.swing.JLabel();
        lblPc17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblPc6 = new javax.swing.JLabel();
        lblPc7 = new javax.swing.JLabel();
        lblPc8 = new javax.swing.JLabel();
        lblPc9 = new javax.swing.JLabel();
        lblPc10 = new javax.swing.JLabel();
        lblPc11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 216, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(182, 191, 210));

        jPanel2.setBackground(new java.awt.Color(208, 216, 232));

        btnPC.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC);

        btnPC1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC1.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC1);

        btnPC2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC2.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC2);

        btnPC3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC3.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC3);

        btnPC4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC4.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC4);

        btnPC5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC5.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel2.add(btnPC5);

        jPanel3.setBackground(new java.awt.Color(208, 216, 232));

        btnPC6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC6.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC6);

        btnPC7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC7.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC7);

        btnPC8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC8.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC8);

        btnPC9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC9.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC9);

        btnPC10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC10.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC10);

        btnPC11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC11.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel3.add(btnPC11);

        jPanel5.setBackground(new java.awt.Color(208, 216, 232));

        btnPC12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC12.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC12);

        btnPC13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC13.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC13);

        btnPC14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC14.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC14);

        btnPC15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC15.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC15);

        btnPC16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC16.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC16);

        btnPC17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pcSelected.png"))); // NOI18N
        btnPC17.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pc.png"))); // NOI18N
        jPanel5.add(btnPC17);

        jPanel6.setBackground(new java.awt.Color(182, 191, 210));

        lblPc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc.setText("          01          ");
        jPanel6.add(lblPc);

        lblPc1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc1.setText("          01          ");
        jPanel6.add(lblPc1);

        lblPc2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc2.setText("          01          ");
        jPanel6.add(lblPc2);

        lblPc3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc3.setText("          01          ");
        jPanel6.add(lblPc3);

        lblPc4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc4.setText("          01          ");
        jPanel6.add(lblPc4);

        lblPc5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc5.setText("          01          ");
        jPanel6.add(lblPc5);

        jPanel8.setBackground(new java.awt.Color(182, 191, 210));

        lblPc12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc12.setText("          01          ");
        jPanel8.add(lblPc12);

        lblPc13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc13.setText("          01          ");
        jPanel8.add(lblPc13);

        lblPc14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc14.setText("          01          ");
        jPanel8.add(lblPc14);

        lblPc15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc15.setText("          01          ");
        jPanel8.add(lblPc15);

        lblPc16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc16.setText("          01          ");
        jPanel8.add(lblPc16);

        lblPc17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc17.setText("          01          ");
        jPanel8.add(lblPc17);

        jPanel9.setBackground(new java.awt.Color(182, 191, 210));

        lblPc6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc6.setText("          01          ");
        jPanel9.add(lblPc6);

        lblPc7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc7.setText("          01          ");
        jPanel9.add(lblPc7);

        lblPc8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc8.setText("          01          ");
        jPanel9.add(lblPc8);

        lblPc9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc9.setText("          01          ");
        jPanel9.add(lblPc9);

        lblPc10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc10.setText("          01          ");
        jPanel9.add(lblPc10);

        lblPc11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPc11.setText("          01          ");
        jPanel9.add(lblPc11);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 1080, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 640, -1, 40));

        jPanel11.setBackground(new java.awt.Color(182, 191, 210));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 42));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, -1, -1));

        jPanel14.setBackground(new java.awt.Color(182, 191, 210));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 280, -1, -1));

        jPanel15.setBackground(new java.awt.Color(182, 191, 210));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChooseComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChooseComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChooseComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChooseComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChooseComputer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilities.MenuButton btnPC;
    private utilities.MenuButton btnPC1;
    private utilities.MenuButton btnPC10;
    private utilities.MenuButton btnPC11;
    private utilities.MenuButton btnPC12;
    private utilities.MenuButton btnPC13;
    private utilities.MenuButton btnPC14;
    private utilities.MenuButton btnPC15;
    private utilities.MenuButton btnPC16;
    private utilities.MenuButton btnPC17;
    private utilities.MenuButton btnPC2;
    private utilities.MenuButton btnPC3;
    private utilities.MenuButton btnPC4;
    private utilities.MenuButton btnPC5;
    private utilities.MenuButton btnPC6;
    private utilities.MenuButton btnPC7;
    private utilities.MenuButton btnPC8;
    private utilities.MenuButton btnPC9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblPc;
    private javax.swing.JLabel lblPc1;
    private javax.swing.JLabel lblPc10;
    private javax.swing.JLabel lblPc11;
    private javax.swing.JLabel lblPc12;
    private javax.swing.JLabel lblPc13;
    private javax.swing.JLabel lblPc14;
    private javax.swing.JLabel lblPc15;
    private javax.swing.JLabel lblPc16;
    private javax.swing.JLabel lblPc17;
    private javax.swing.JLabel lblPc2;
    private javax.swing.JLabel lblPc3;
    private javax.swing.JLabel lblPc4;
    private javax.swing.JLabel lblPc5;
    private javax.swing.JLabel lblPc6;
    private javax.swing.JLabel lblPc7;
    private javax.swing.JLabel lblPc8;
    private javax.swing.JLabel lblPc9;
    // End of variables declaration//GEN-END:variables
}
