/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import businessObjects.LaboratoryBO;
import dto.AcademyDTO;
import dto.LaboratoryDTO;
import exception.BusinessException;
import frames.FrmLaboratoryManager;
import interfaces.IAcademyUnityBO;
import interfaces.ILaboratoryBO;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */

public class FrmUpdateLaboratoryManager extends javax.swing.JFrame {

    ILaboratoryBO laboratoryBO;
    IAcademyUnityBO academyBO;
    LaboratoryDTO laboratoryDTO;

    /**
     * Creates new form FrmStudentManager
     */
    public FrmUpdateLaboratoryManager(ILaboratoryBO laboratoryBO, IAcademyUnityBO academyBO, LaboratoryDTO laboratorioDTO ) {
        initComponents();
        this.academyBO = academyBO;
        this.laboratoryBO = laboratoryBO;
        this.laboratoryDTO=laboratorioDTO;
        this.loadFrame();
    }

    public void loadFrame() {
        this.setTitle("Editar Laboratorios ");
        this.setResizable(false);
        this.setSize(598, 600);
        this.setLocationRelativeTo(null);
        this.fillFields();

    }

    private void fillFields(){
        txtName.setText(laboratoryDTO.getLabName());
        txtStartTime.setText(laboratoryDTO.getStartTime().toString());
        txtEndTime.setText(laboratoryDTO.getEndTime().toString());
        txtPasswordMaster.setText(laboratoryDTO.getMasterPassword());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menuButton13 = new utilities.MenuButton();
        lbNewLaboratory = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        javax.swing.JLabel lblStartTime = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        txtEndTime = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        txtPasswordMaster = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(208, 216, 232));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(menuButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 857, -1, -1));

        lbNewLaboratory.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbNewLaboratory.setText("Editar Laboratorio");
        jPanel4.add(lbNewLaboratory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 340, -1));

        lblEndTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEndTime.setText("Hora de Cierre:");
        jPanel4.add(lblEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        lblStartTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStartTime.setText("Hora de Apertura:");
        jPanel4.add(lblStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPassword.setText("Contraseña:");
        jPanel4.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblName.setText("Nombre:");
        jPanel4.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnContinue.setText("Continuar");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        jPanel4.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, 40));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 250, 30));
        jPanel4.add(txtStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 250, 30));
        jPanel4.add(txtEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 250, 30));

        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel4.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 170, 40));
        jPanel4.add(txtPasswordMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 250, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String labName = txtName.getText().trim();
        String startTimeTexto = txtStartTime.getText().trim();
        String endTimeTexto = txtEndTime.getText().trim();
        String masterPassword = txtPasswordMaster.getText().trim();

        if (labName.isEmpty() || startTimeTexto.isEmpty() || endTimeTexto.isEmpty() || masterPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalTime startTime;
        try {
            startTime = LocalTime.parse(startTimeTexto, DateTimeFormatter.ofPattern("HH:mm"));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de hora inválido: " + startTimeTexto + ". Usa el formato HH:mm.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalTime endTime;
        try {
            endTime = LocalTime.parse(endTimeTexto, DateTimeFormatter.ofPattern("HH:mm"));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de hora inválido: " + endTimeTexto + ". Usa el formato HH:mm.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LaboratoryDTO newLaboratoryDTO = new LaboratoryDTO(this.laboratoryDTO.getId(), labName, startTime, endTime, masterPassword, this.laboratoryDTO.getIdAcademy());

        
        try {
            laboratoryBO.updateLaboratory(newLaboratoryDTO);
        } catch (BusinessException ex) {
            Logger.getLogger(FrmUpdateLaboratoryManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Laboratorio editado con éxito.");
        this.setVisible(false);
        FrmLaboratoryManager laboratory = new FrmLaboratoryManager(laboratoryBO, academyBO);
        laboratory.setVisible(true);
    
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmLaboratoryManager laboratory = new FrmLaboratoryManager(laboratoryBO, academyBO);
        laboratory.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbNewLaboratory;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private utilities.MenuButton menuButton13;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPasswordMaster;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}

