/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import businessObjects.DegreeBO;
import businessObjects.LaboratoryBO;
import dto.AcademyDTO;
import dto.LaboratoryDTO;
import dto.StudentDTO;
import enums.EnrollmentStatus;
import exception.BusinessException;
import frames.FrmLaboratoryManager;
import interfaces.IAcademyUnityBO;
import interfaces.IDegreeBO;
import interfaces.ILaboratoryBO;
import interfaces.IStudentBO;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class FrmUpdateStudentManager extends javax.swing.JFrame {

    StudentDTO studentDTO;
    IStudentBO studentBO;
    IDegreeBO degreeBO;
    EnrollmentStatus enrollmentStatus;
    List<StudentDTO> studentList;

    /**
     * Creates new form FrmStudentManager
     */
    public FrmUpdateStudentManager(StudentDTO studentDTO, IStudentBO studentBO) {
        this.enrollmentStatus = enrollmentStatus;
        initComponents();
        this.studentBO = studentBO;
        this.enrollmentStatus = EnrollmentStatus.Inscrito;
        this.studentDTO = studentDTO;
        this.studentList = new ArrayList<>();
        this.loadFrame();
    }

    public void loadFrame() {
        this.setTitle("Editar Estudiantes ");
        this.setResizable(false);
        this.setSize(598, 600);
        this.setLocationRelativeTo(null);
        this.fillFields();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        this.llenarComboClasificaciones();
//        this.fillStatusComboBox();

    }

    private void fillFields() {
        txtName.setText(studentDTO.getNames());
        txtLastName.setText(studentDTO.getFirstLastname());
        txtSecondName.setText(studentDTO.getSecondLastname());
        txtPassword.setText(studentDTO.getPassword());

    }

//    private void llenarComboClasificaciones() {
//        for (enrollmentStatus clasi : enrollmentStatus.values()) {
//            cbStatus.addItem(clasi);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        menuButton13 = new utilities.MenuButton();
        lbUpdateStudent = new javax.swing.JLabel();
        lblSecondName = new javax.swing.JLabel();
        javax.swing.JLabel lblLastName = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSecondName = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword1 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(208, 216, 232));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(menuButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 857, -1, -1));

        lbUpdateStudent.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbUpdateStudent.setForeground(new java.awt.Color(0, 0, 0));
        lbUpdateStudent.setText("Editar Estudiante");
        jPanel4.add(lbUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 340, -1));

        lblSecondName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSecondName.setForeground(new java.awt.Color(0, 0, 0));
        lblSecondName.setText("Apellido Materno:");
        jPanel4.add(lblSecondName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, -1));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(0, 0, 0));
        lblLastName.setText("Apellido Paterno:");
        jPanel4.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Estado:");
        jPanel4.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Nombre:");
        jPanel4.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnContinue.setText("Continuar");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        jPanel4.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 170, 40));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 250, 30));
        jPanel4.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 250, 30));
        jPanel4.add(txtSecondName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 250, 30));

        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel4.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 170, 40));
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 250, 30));

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword1.setText("Contraseña:");
        jPanel4.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        cbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        jPanel4.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 250, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String studentName = txtName.getText().trim();
        String studentLastName = txtLastName.getText().trim();
        String studentSecondName = txtSecondName.getText().trim();
        String password = txtPassword.getText().trim();

        if (studentName.isEmpty() || studentLastName.isEmpty() || studentSecondName.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StudentDTO newStudentDTO = new StudentDTO(this.studentDTO.getUnique_ID(), studentName, studentLastName, studentSecondName, password);

        try {
            studentBO.updateStudent(studentDTO);
        } catch (BusinessException ex) {
            Logger.getLogger(FrmUpdateStudentManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Estudiante editado con éxito.");
        this.setVisible(false);
        FrmStudentManager student = new FrmStudentManager(studentBO, degreeBO);
        student.setVisible(true);

    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed

    }//GEN-LAST:event_btnReturnActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbUpdateStudent;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblSecondName;
    private javax.swing.JLabel lblStatus;
    private utilities.MenuButton menuButton13;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecondName;
    // End of variables declaration//GEN-END:variables
}
